config/routes.rb
Rails.application.routes.draw do
  
  resources :newsfeeds
  resources :newsfeeds
  resources :newsfeeds
  resources :newsfeeds
  get '/logged' => 'logged#index'

  resources :extensions
  devise_for :users
  

authenticated :user do
  root :to => "logged#index", as: :authenticated_root
end

  root :to => 'welcome#index'

  get '/about' => 'welcome#about'

end

app/models/extension.rb
class Extension < ActiveRecord::Base
	validates :extension, presence: true, uniqueness: true
end

app/models/newsfeed.rb
class Newsfeed < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true, uniqueness: true
	validates :body, presence: true, length: { minimum: 20 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :newsfeeds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/extensions_controller.rb
class ExtensionsController < ApplicationController
  before_action :set_extension, only: [:show, :edit, :update, :destroy]

  # GET /extensions
  # GET /extensions.json
  def index
    @extensions = Extension.all
  end

  # GET /extensions/1
  # GET /extensions/1.json
  def show
  end

  # GET /extensions/new
  def new
    @extension = Extension.new
  end

  # GET /extensions/1/edit
  def edit
  end

  # POST /extensions
  # POST /extensions.json
  def create
    @extension = Extension.new(extension_params)

    respond_to do |format|
      if @extension.save
        format.html { redirect_to @extension, notice: 'Extension was successfully created.' }
        format.json { render :show, status: :created, location: @extension }
      else
        format.html { render :new }
        format.json { render json: @extension.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extensions/1
  # PATCH/PUT /extensions/1.json
  def update
    respond_to do |format|
      if @extension.update(extension_params)
        format.html { redirect_to @extension, notice: 'Extension was successfully updated.' }
        format.json { render :show, status: :ok, location: @extension }
      else
        format.html { render :edit }
        format.json { render json: @extension.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extensions/1
  # DELETE /extensions/1.json
  def destroy
    @extension.destroy
    respond_to do |format|
      format.html { redirect_to extensions_url, notice: 'Extension was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extension
      @extension = Extension.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def extension_params
      params.require(:extension).permit(:extension, :name, :email, :department)
    end
end

app/controllers/logged_controller.rb
class LoggedController < ApplicationController
  def index
  	@newsfeeds = Newsfeed.all
  	@piech=Gchart.pie(:data => [120, 45, 25, 55, 20])

  end
end

app/controllers/newsfeeds_controller.rb
class NewsfeedsController < ApplicationController
  before_action :set_newsfeed, only: [:show, :edit, :update, :destroy]

  # GET /newsfeeds
  # GET /newsfeeds.json
  def index
    @newsfeeds = Newsfeed.all
  end

  # GET /newsfeeds/1
  # GET /newsfeeds/1.json
  def show
  end

  # GET /newsfeeds/new
  def new
    @newsfeed = Newsfeed.new
  end

  # GET /newsfeeds/1/edit
  def edit
  end

  # POST /newsfeeds
  # POST /newsfeeds.json
  def create
    @newsfeed = current_user.newsfeeds.new(newsfeed_params)

    respond_to do |format|
      if @newsfeed.save
        format.html { redirect_to @newsfeed, notice: 'Newsfeed was successfully created.' }
        format.json { render :show, status: :created, location: @newsfeed }
      else
        format.html { render :new }
        format.json { render json: @newsfeed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsfeeds/1
  # PATCH/PUT /newsfeeds/1.json
  def update
    respond_to do |format|
      if @newsfeed.update(newsfeed_params)
        format.html { redirect_to @newsfeed, notice: 'Newsfeed was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsfeed }
      else
        format.html { render :edit }
        format.json { render json: @newsfeed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsfeeds/1
  # DELETE /newsfeeds/1.json
  def destroy
    @newsfeed.destroy
    respond_to do |format|
      format.html { redirect_to newsfeeds_url, notice: 'Newsfeed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsfeed
      @newsfeed = Newsfeed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsfeed_params
      params.require(:newsfeed).permit(:title, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/extensions_helper.rb
module ExtensionsHelper
end

app/helpers/logged_helper.rb
module LoggedHelper
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/extensions/_form.html.erb
<%= form_for(@extension) do |f| %>
  <% if @extension.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@extension.errors.count, "error") %> prohibited this extension from being saved:</h2>

      <ul>
      <% @extension.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :extension %><br>
    <%= f.number_field :extension %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/extensions/edit.html.erb
<h1>Editing Extension</h1>

<%= render 'form' %>

<%= link_to 'Show', @extension %> |
<%= link_to 'Back', extensions_path %>

app/views/extensions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Extensions</h1>
<hr/>
<table>
  <thead>
    <tr>
      <th>Extension</th>
      <th>Name</th>
      <th>Email</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @extensions.each do |extension| %>
      <tr>
        <td><%= extension.extension %></td>
        <td><%= extension.name %></td>
        <td><%= extension.email %></td>
        <td><%= extension.department %></td>
        <td></td>
        <td><%= link_to 'Show', extension %></td>
        <td><% link_to 'Edit', edit_extension_path(extension) %></td>
        <td><% link_to 'Destroy', extension, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<hr/>
<%= link_to 'New Extension', new_extension_path %>

app/views/extensions/new.html.erb
<h1>New Extension</h1>

<%= render 'form' %>

<%= link_to 'Back', extensions_path %>

app/views/extensions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Extension:</strong>
  <%= @extension.extension %>
</p>

<p>
  <strong>Name:</strong>
  <%= @extension.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @extension.email %>
</p>

<p>
  <strong>Department:</strong>
  <%= @extension.department %>
</p>

<%= link_to 'Edit', edit_extension_path(@extension) %> |
<%= link_to 'Back', extensions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>AC Corp. Intranet</title>
	  <link href='https://fonts.googleapis.com/css?family=Play' rel='stylesheet' type='text/css'>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
	<header>
		<nav class="be-ylw blkfnt large-padding">
			<ul class="no-list row center-xs middle-xs nav">
				
					<li class="col-md">
						<h1 class="no-margin" id="logo"><%= link_to "AC Corp.", root_path, class:'nav_lnk_color' %></h1>
					</li>

					<li class="col-md">
						<%= link_to raw("<i class=\"glyphicon glyphicon-home\"></i> Home"), root_path, class:'nav_lnk_color' %>
					</li>
					<li class="col-md">
						<%= link_to raw("<i class=\"glyphicon glyphicon-globe\"></i> About AC Corp."), about_path, class:'nav_lnk_color' %>
					</li>
				
				<% if user_signed_in? %>
					<li class="col-md">
						<%= link_to raw("<i class=\"glyphicon glyphicon-list\"></i> Phone Directory"), extensions_path, class:'nav_lnk_color' %>
					</li>
					<li class="col-md">
						<%= link_to raw("<i class=\"glyphicon glyphicon-envelope\"></i> Mail"), "https://mail.google.com", class:'nav_lnk_color', target: '_blank' %>
					</li>

					<li class="col-md">
						<%= link_to raw("<i class=\"glyphicon glyphicon-user\"></i> Logout"), destroy_user_session_path, method: :delete, class:'nav_lnk_color' %>
					</li>
					<li class="col-md">
						Logged in as: <%= current_user.email %>
					</li>
				<% else %>
					
					<li class="col-md">
						<%= link_to raw("<i class=\"glyphicon glyphicon-user\"></i> Log-in"), new_user_session_path, class:'nav_lnk_color' %>
					</li>
					
				<% end %>				 
			</ul>
		</nav>
	</header>		
		<div class="marco">
			<p class="notice"><%= notice %></p>
      		<p class="alert"><%= alert %></p>
			<%= yield %>
		</div>
		<footer class="marco"><br/>© 2016 Corwyn82.</footer>
	</body>
</html>

app/views/logged/index.html.erb
<%= image_tag "bgloged.jpg", class: 'img' %>

<div class="row">
	<div class="col-md">
		<h1 class="orange_lnk">Welcome to the Generic Intranet Portal!</h1>
		<p>
			This is an example of the logged webpage you'll get here whenever you are logged in
		</p>
	</div>
</div>
<div class="row">
	<div class="col-md">
		<h4>Links to Department pages</h4>
		<ul class="orange_lnk">
			<li>Human Resources</li>
			<li>Accounting</li>
			<li>Purchasing and Sales</li>
			<li>Receiving and Shipping</li>
			<li>Warehouse</li>
			<li>Production</li>
			<li>Engineering</li>
			<li>IT</li>
			<li>Marketing</li>
		</ul>
	</div>
	<div class="col-md">
		<h4>Newsfeed</h4>
		<table>
		  
		  <tbody>
		      <% @newsfeeds.last(4).reverse_each do |newsfeed| %>
		      <tr>
		        <td><div class="orange_lnk"><%= newsfeed.title %></div><%= newsfeed.body %><br/>by <%= newsfeed.user.email %></td>
		        <td></td>
		       </td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
		<br>

		<%= link_to 'See all', newsfeeds_path, class:'orange_lnk' %> <%= link_to 'Create Article', new_newsfeed_path, class:'orange_lnk' %>

	</div>
	<div class="col-md">
		<h4>Production Report</h4>
		<br/>
		<%= image_tag @piech %>
	</div>
</div>
<hr/>

app/views/newsfeeds/_form.html.erb
<%= form_for(@newsfeed) do |f| %>
  <% if @newsfeed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newsfeed.errors.count, "error") %> prohibited this newsfeed from being saved:</h2>

      <ul>
      <% @newsfeed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newsfeeds/edit.html.erb
<h1>Editing Newsfeed</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsfeed %> |
<%= link_to 'Back', newsfeeds_path %>

app/views/newsfeeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Newsfeeds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newsfeeds.reverse_each do |newsfeed| %>
      <tr>
        <td><%= newsfeed.title %></td>
        <td><%= newsfeed.body %></td>
        <td><%= link_to 'Show', newsfeed %></td>
        <td><%= link_to 'Edit', edit_newsfeed_path(newsfeed) %></td>
        <td><%= link_to 'Destroy', newsfeed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newsfeed', new_newsfeed_path %>

app/views/newsfeeds/new.html.erb
<h1>New Newsfeed</h1>

<%= render 'form' %>

<%= link_to 'Back', newsfeeds_path %>

app/views/newsfeeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @newsfeed.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @newsfeed.body %>
</p>

<%= link_to 'Edit', edit_newsfeed_path(@newsfeed) %> |
<%= link_to 'Back', newsfeeds_path %>

app/views/welcome/about.html.erb
<div class="row centraTodo">
	<div>
	   <%= image_tag "jlw.png"%>
	</div>
	<div class="col-md">
	   <h1  class="orange_lnk">Jose L. Wong</h1>
	<p>A self-starter with entrepreneurial spirit and a quick learner. With a versatile skill set and 11 years’ experience in different fields including Manufacture, Banking, Maritime Logistics, Industrial Recycling of Metals, Government, Oil Industry, Sales and Educational. Background include 9+ years’ experience in Computer Programming, Project Management, Database Management, Network Management, Structured Cable, Setup and Management of Telecommunications as well as 3+ years’ experience in developing, auditing and implementing quality systems complying with ISO 27001, ISO 9001, ISO 14001 and OSHAS 18001, customer service, sales and business development. Always oriented to increase company's and self-growth.

	<h3 class="orange_lnk">Capacity summary</h3>
		<ul class='dsk'>
          <li>Ruby on Rails, .NET, JSP, ASP, PHP Web development</li>
          <li>VB.NET, C#, WPF, JAVA software development</li>
          <li>Project Management</li>
          <li>Database Administration</li>
          <li>Logistic programming</li>
          <li>Quality Management Systems Implementation</li>
          <li>Technical support</li>
          <li>Network Installation and Support</li>
          <li>Preventive and corrective maintenance for computer equipment</li>
          <li>Fluent in Spanish and English</li>
        </ul>

       <hr/></p>
       <p style="text-align:right;">
       	<%= link_to image_tag('email-1.png', height: '32', width: '32'), 'mailto:jlwong.ac@gmail.com', class:'nada'%>&nbsp;<%= link_to image_tag('linkedin.png', height: '32', width: '32'), 'https://mx.linkedin.com/in/jlwong82', class:'nada', target: '_blank' %>&nbsp;<%= link_to image_tag('facebook.png', height: '32', width: '32'), 'https://www.facebook.com/jlwong82', class:'nada', target: '_blank' %>&nbsp;<%= link_to image_tag('twitter.png', height: '32', width: '32'), 'https://twitter.com/jlwong82', class:'nada', target: '_blank' %>
	</p>
	</div>

</div>

app/views/welcome/index.html.erb
<%= image_tag "bghome.jpg", class: 'img' %>
<h1 class="orange_lnk">Welcome to the Generic Intranet Portal!</h1>
<hr/>
<p>
This is an example for what can be built using Ruby on Rails, you can Register to test the webpage at the nav-bar option Register, or Log in if you have already created an account.
<br/><br/>
Being registered gives you access to more features as you could be able to add Phone Extensions or update the newsfeed.
<br/><br/>
Please be sure to visit the about page to learn more from the creator and how to get in touch.
</p>